---
# 1. Install essential packages (Handles Ubuntu and Fedora)
- name: Install required packages on Ubuntu
  ansible.builtin.apt:
    name:
      - tmux
      - vim
      - neovim
      - curl
      - git
      - fonts-powerline
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Install required packages on Fedora
  ansible.builtin.dnf:
    name:
      - tmux
      - vim
      - neovim
      - curl
      - git
      - powerline-fonts
    state: present
  when: ansible_os_family == "RedHat"

# 2. Ensure ~/.config and ~/.config/dotfiles exist
- name: Ensure directory structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "~/.config"
    - "~/.config/dotfiles"

# 3. Append source logic to original .bashrc
- name: Append sourcing logic to .bashrc
  ansible.builtin.lineinfile:
    path: "~/.bashrc"
    line: 'if [ -f ~/.config/dotfiles/.bashrc_extension ]; then source ~/.config/dotfiles/.bashrc_extension; fi'
    state: present

# 4. Create symlinks for dotfiles
- name: Symlink dotfiles to their respective locations
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "~/.config/dotfiles/.bash_aliases", dest: "~/.bash_aliases" }
    - { src: "~/.config/dotfiles/.vimrc", dest: "~/.vimrc" }
    - { src: "~/.config/dotfiles/.tmux.conf", dest: "~/.tmux.conf" }

# 5. Install vim-plug for Vim
- name: Install vim-plug
  ansible.builtin.command:
    cmd: "curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    creates: "~/.vim/autoload/plug.vim"

# 6. Install Vim plugins
- name: Install Vim plugins
  ansible.builtin.command:
    cmd: "vim +PlugInstall +qall"
  args:
    creates: "~/.vim/plugged/vim-airline"

# 7. Clone Tmux Plugin Manager (TPM)
- name: Clone Tmux Plugin Manager (TPM)
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "~/.tmux/plugins/tpm"
    version: main

# 8. Install Tmux plugins using TPM
- name: Install Tmux plugins using TPM
  ansible.builtin.command:
    cmd: "~/.tmux/plugins/tpm/bin/install_plugins"
  args:
    creates: "~/.tmux/plugins/tmux-resurrect"
